name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run
      if: runner.os == 'Linux'
      run: npm run pretest && xvfb-run -a npm run test:cc

    - name: Run
      if: runner.os != 'Linux'
      run: npm run pretest && npm run test:cc

    - name: Check Coverage
      if: runner.os == 'Linux'
      run: npm run test:ensure-coverage
